version: "3.7"
services:
  application:
    build:
        target: dev
        dockerfile: .docker/Dockerfile
        context: ..
        args:
            CURRENT_UID: ${CURRENT_UID}
    container_name: ${COMPOSE_PROJECT_NAME}-application
    restart: on-failure
    volumes:
      - ../:/app
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    working_dir: /app
    tty: true
    ports:
      - 8080:8080
      - 9180:9180