version: "3.7"
services:
  application:
    image: ${APP_IMAGE}
    build:
        target: dev
        dockerfile: .docker/Dockerfile
        context: ..
        args:
            DEVELOPER_UID: ${DEVELOPER_UID}
    container_name: ${CONTAINER_NAME}
    restart: on-failure
    volumes:
      - ../:/app
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    working_dir: /app
    tty: true
    ports:
      - 8080:8080